### ISSUE TITLE
clear console

### ISSUE THREAD

**Issue by ken-blocklevel** [petruisfan/node-supervisor#169]
This is a suggestion:

Have a flag which when given on start, clears console before restart on file change.

I've found when debugging a server, the console can get really polluted with console.logs and debug messages. If console would be cleared before restarting this is not the case.

**Comment by petruisfan** [comment]
Thank you for your suggestion. I think this is too much of a burden for the value it ads to the product. To find a solution that is cross platform for cleaning console output would be a lot of work, and the value added is not that much. I would rather concentrate the efforts into solving other open issues. But feel free to submit a pull request :) Otherwise closing issue.

**Comment by ken-blocklevel** [comment]
Alright, good feedback. Thanks for replying and I might do that ;)
