### ISSUE TITLE
CPU spike for 2500 watched files in v0.8.8

### ISSUE THREAD

**Issue by nemtsov** [petruisfan/node-supervisor#71]
When watching a large number of files (a bit more than 2500 in my specific case) with `supervisor -e 'js|mu' app` the CPU spikes to 60% on MBP 2.2Ghz. I repeated the same with `forever --spinSleepTime 10 --watch --watchDirectory . start app.js` and the CPU remained roughly at 0%.

**Comment by DinisCruz** [comment]
I was having the same prob with a significant CPU usage when using supervisor. This was a minor prob in dev and major prob when running multiple docker instances (of the same site) , since that meant that each new docker container added was consuming a bit of the CPU (which added up quite quickly to a substantial part of the CPU being used just to 'watch')

**Comment by jklepp-tgm** [comment]
Supervisor  uses up 130% CPU according to htop.

Same application ran directly by node drops to 0% CPU usage after 2 seconds upstart time.
