### ISSUE TITLE
Error while starting supervisor for CoffeeScript file

### ISSUE THREAD

**Issue by extesy** [petruisfan/node-supervisor#83]
Using command line like "supervisor server.coffee" I get this error (node.js v0.9.3):

<pre>DEBUG: Running node-supervisor with
DEBUG:   program 'server.coffee'
DEBUG:   --watch '.'
DEBUG:   --ignore 'undefined'
DEBUG:   --extensions 'node|js|coffee'
DEBUG:   --exec 'coffee'

DEBUG: Starting child process with 'coffee server.coffee'
DEBUG: Watching directory 'C:\wamp\www\foos2' for changes.

events.js:68
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: spawn ENOENT
    at errnoException (child_process.js:868:11)
    at Process.ChildProcess._handle.onexit (child_process.js:680:34)
    at process._makeCallback (node.js:248:20)</pre>

Any idea what might be wrong? It works fine when I use it for server.js file.

**Comment by robert-blankenship** [comment]
@extesy I saw the exact same exception, but on Ubuntu 14.04

For me, the issue was that I didn't have `coffee` installed globally (but it was present in node_modules). `supervisor` was installed globally. 

Doing `sudo npm install -g coffee-script` fixed it for me.

@KamilSzot I didn't look at your PR. But your problem sounds similar - `coffee` is working like `supervisor` expects it to. I would think that simply testing for the existence of the coffee executable and checking if it's executable would be enough. In essence:
```coffeescript
operatingSystemPathName = "$PATH" or #whatever Windows does.
compilerName = 'CoffeeScript' or 'TypeScript'
compilerBinName = 'coffee' or #typescripts executable name

if not shell_exec(compilerBinName)
    throw "Could not find the #{compilerName} executable #{compilerBinName} in the #{operatingSystemPathName}."
```
@iangreenleaf There are many versions of CoffeeScript (and TypeScript) out there, and many ways of using them. It's not too out of the ordinary to keep the CoffeeScript files in the node_modules folder

**Comment by luochen1990** [comment]
@robert-blankenship +1, I prefer to install node packages locally and use `package.json/scripts` and `npm run` command to use utils. I think this way should be supported :)
